spring.datasource.url=jdbc:postgresql://localhost:5432/receipt_db
spring.datasource.username=postgres
spring.datasource.password=Bank2026

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
file.upload-dir=uploads